name: 'build' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          # Change this to point to your image name
          imageName: ghcr.io/forestsoftgmbh/devcontainer
          cacheFrom: forestsoft/devcontainer:latest
          subFolder: base
          push: always
        
  build_application_containers:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: ["php", "golang"]
    steps:  
      - name: Build Application
        uses: devcontainers/ci@v0.3
        with:
          # Change this to point to your image name
          imageName: ghcr.io/forestsoftgmbh/devcontainer/${{ matrix.type }}
          cacheFrom: forestsoft/devcontainer:latest
          subFolder: ${{ matrix.type }}/
          push: always  
